### ISSUE TITLE
React Cover Up Text Field

### ISSUE THREAD

**Issue by finreinhard** [micromata/projectforge#71]

**Comment by finreinhard** [comment]
/react/dynamic/cardDAVInfo

**Comment by finreinhard** [comment]
https://github.com/micromata/projectforge/tree/feature/71-card-dav-info

# ToDo
- [X] Cover Up Field
- [X] CardDavInfoPage Read Only Fields
- [ ] CardDavInfoPage Translations
- [ ] CardDavInfoPage Real Values
